### PR TITLE
fix import path

### PR DESCRIPTION
**Pull request by nijkah**
**mmcv.cnn.weight_init** was moved to **mmcv.cnn.utils**

### CODE REVIEW

**Comment by JamesMcDougallJr** [comment]
Can confirm this works. Using Python3.6, PyTorch 1.1.0.

**Comment by nijkah** [comment]
https://github.com/open-mmlab/mmcv/blob/master/mmcv/cnn/__init__.py
https://github.com/open-mmlab/mmcv/blob/master/mmcv/cnn/utils/weight_init.py

Recent mmcv.cnn does not include weight_init module directly.
How is it possible?

Or, it could be possible to specify the version of old mmcv.

**Comment by JamesMcDougallJr** [comment]
> 
> 
> https://github.com/open-mmlab/mmcv/blob/master/mmcv/cnn/__init__.py
> https://github.com/open-mmlab/mmcv/blob/master/mmcv/cnn/utils/weight_init.py
> 
> Recent mmcv.cnn does not include weight_init module directly.
> How is it possible?
> 
> Or, it could be possible to specify the old version of mmcv in requirements.txt.

Wouldn't it be better to upgrade this repository to support the latest version of mmcv? Especially because it is only one line that seems to need to be changed.

Or, add an if statement based on the version of mmcv, to switch between the two import statements?

**Comment by nijkah** [comment]
Okay, then how about specifying the version of mmcv used in this repository in requirements.txt?

Due to this one line, new practitioners always have to face syntax error and spend time to deal with it by fixing the code or finding the appropriate version of mmcv.

**Pull request closed without merging**
